export const categories = [
  {
    slug: "pasteis-tradicionais",
    icon: "🥟",
    title: "Pastéis Tradicionais",
    desc: "Massa fina e crocante, recheio generoso, fritos na hora do pedido.",
  },
  {
    slug: "pasteis-especiais",
    icon: "⭐",
    title: "Pastéis Especiais",
    desc: "Camarão, palmito e a receita especial da casa.",
  },
  {
    slug: "pasteis-doces",
    icon: "🍫",
    title: "Pastéis Doces",
    desc: "Pra fechar com chave de ouro: chocolate, banana e muito mais.",
  },
  {
    slug: "adicionais",
    icon: "➕",
    title: "Adicionais",
    desc: "Catupiry, queijo, bacon e molho extra pra completar o pedido.",
  },
  {
    slug: "salgados",
    icon: "🍗",
    title: "Salgados",
    desc: "Coxinha, risole, kibe e outros clássicos do balcão.",
  },
  {
    slug: "bebidas",
    icon: "🥤",
    title: "Bebidas",
    desc: "Refrigerantes e sucos geladinhos pra acompanhar.",
  },
  {
    slug: "sorvetes",
    icon: "🍦",
    title: "Sorvetes",
    desc: "Casquinha, copinho e milk-shake pra sobremesa.",
  },
  {
    slug: "caldo-de-cana",
    icon: "🎋",
    title: "Caldo de Cana",
    desc: "Moído na hora, com limão ou maracujá se você preferir.",
  },
];

export const menu = [
  {
    slug: "pasteis-tradicionais",
    icon: "🥟",
    title: "Pastéis Tradicionais",
    items: [
      { name: "Carne", desc: "Recheio de carne moída", price: "R$ 9,50" },
      { name: "Frango", desc: "Recheio de Frango", price: "R$ 9,50" },
      { name: "Queijo c/ Catupiry", desc: "Recheio de queijo", price: "R$ 9,50" },
      { name: "Pizza", desc: "Recheio de queijo presunto tomate e orégano", price: "R$ 9,50" },
      { name: "Calabresa", desc: "Calabresa moída com cebola", price: "R$ 10,00" },
    ],
  },
  {
    slug: "pasteis-especiais",
    icon: "⭐",
    title: "Pastéis Especiais",
    items: [
      { name: "Especial de carne", desc: "Carne, queijo, palmito, milho e ovo", price: "R$ 15,00" },
      { name: "Especial de frango", desc: "Frango, queijo, calabressa e milho", price: "R$ 15,00" },
      { name: "Especial de pizza", desc: "Presunto, queijo, tomate, orégano e cheedar ou catupiry", price: "R$ 15,00" },
      { name: "Especial de palmito", desc: "Palmito, queijo e calabressa", price: "R$ 15,00" },
    ],
  },
  {
    slug: "pasteis-doces",
    icon: "🍫",
    title: "Pastéis Doces",
    items: [
      { name: "Chocolate", desc: "Chocolate ao leite derretido", price: "R$ 10,50" },
      { name: "Banana com Canela", desc: "Banana com canela", price: "R$ 10,50" },
      { name: "Romeu e Julieta", desc: "Goiabada com queijo derretido", price: "R$ 10,50" },
      { name: "Dois amores", desc: "Chocolate ao leite e chocolate branco", price: "R$ 10,50" },
    ],
  },
  {
    slug: "salgados",
    icon: "🍗",
    title: "Salgados",
    items: [
      { name: "Coxinha", desc: "Frango", price: "R$ 7,00" },
      { name: "Coxinha com catupiry", desc: "Frango com catupiry", price: "R$ 7,50" },
      { name: "Coxinha com cheedar", desc: "Frango com cheedar", price: "R$ 7,50" },
      { name: "Bolinho de carne", desc: "", price: "R$ 7,00" },
      { name: "Kibe", desc: "Trigo e carne", price: "R$ 7,00" },
    ],
  },
  {
    slug: "Porções",
    icon: "🍗",
    title: "Porções",
    items: [
      { name: "Fritas", desc: "Batatas fritas", price: "R$ 23,00" },
      { name: "Fritas com bacon", desc: "Batatas fritas com bacon", price: "R$ 28,00" },
      { name: "Fritas com bacon e chhedar", desc: "Batatas fritas com bacon e chhedar", price: "R$ 32,00" },
      { name: "Fritas com calabresa", desc: "Batatas fritas com calabresa", price: "R$ 39,00" },
      { name: "Calabresa", desc: "calabresa", price: "R$ 30,00" },
      { name: "Completa", desc: "Batatas com bacon, cheddar e calabresa", price: "R$ 49,00" },
      { name: "Completíssima", desc: "Batatas com bacon, cheddar, calabresa", price: "R$ 69,00" },
      { name: "Mandioca", desc: "Mandioca", price: "R$ 24,00" },
      { name: "Mandioca com bacon", desc: "Mandioca com bacon", price: "R$ 29,00" },
      { name: "Mandioca com calabresa", desc: "Mandioca com calabresa", price: "R$ 42,00" },
      { name: "Mandioca com bacon e cheddar", desc: "Mandioca com bacon e cheddar", price: "R$ 49,00" },
      { name: "Iscas de peixe", desc: "Iscas de peixe", price: "R$ 45,00" },
      { name: "Tilapia", desc: "Tilapia", price: "R$ 54,00" },
    ],
  },
  {
    slug: "adicionais",
    icon: "➕",
    title: "Adicionais",
    items: [
      { name: "Azeitona ou milho", desc: "Azeitona ou milho extra pra colocar no seu pastel", price: "R$ 2,00" },
      { name: "Cheddar ou catupiry", desc: "Cheddar ou catupiry extra pra colocar no seu pastel", price: "R$ 2,50" },
      { name: "Bacon", desc: "Bacon extra pra colocar no seu pastel", price: "R$ 3,50" },
      { name: "Queijo", desc: "Queijo extra pra colocar no seu pastel", price: "R$ 3,00" },
      { name: "Ovo", desc: "Ovo extra pra colocar no seu pastel", price: "R$ 2,00" },
      { name: "Calabresa", desc: "Calabresa extra pra colocar no seu pastel", price: "R$ 3,00" },
      { name: "Palmito", desc: "Palmito extra pra colocar no seu pastel", price: "R$ 2,50" },
      { name: "Chocolate", desc: "Chocolate extra pra colocar no seu pastel", price: "R$ 3,00" },
    ],
  },
  {
    slug: "Churros",
    icon: "🎋",
    title: "Churros",
    items: [
      { name: "Doce de leite", desc: "Churros de doce de leite", price: "R$ 7,00" },
      { name: "Chocolate", desc: "Churros de chocolate", price: "R$ 7,00" },
    ]
  },
  {
    slug: "bebidas",
    icon: "🥤",
    title: "Bebidas",
    items: [
      { name: "Água", desc: "Agua sem gás", price: "R$ 3,50" },
      { name: "Água gás", desc: "Agua com gás", price: "R$ 4,00" },
      { name: "Café", desc: "Copo de café", price: "R$ 4,00" },
      { name: "Café com leite", desc: "Copo de café com leite", price: "R$ 5,50" },
      { name: "Nescau", desc: "Copo de Nescau", price: "R$ 6,50" },
      { name: "Todino", desc: "Caixinha de Todino", price: "R$ 3,50" },
      { name: "Choco Milk", desc: "Caixinha de Choco Milk", price: "R$ 6,00" },
      { name: "Kapo", desc: "Caixinha de Kapo", price: "R$ 5,50" },
      { name: "Refri 200 ml", desc: "Refrigerante de 200ml", price: "R$ 3,50" },
      { name: "Refri lata", desc: "Refrigerante de lata", price: "R$ 5,50" },
      { name: "Tampico", desc: "Tampico de 450ml", price: "R$ 6,00" },
      { name: "Coca", desc: "Coca de 600ml", price: "R$ 9,50" },
      { name: "Guaraná", desc: "Guaraná de 1 L", price: "R$ 10,00" },
      { name: "Guaraná 1,5 L", desc: "Guaraná de 1,5 L", price: "R$ 11,50" },
      { name: "Coca 2 L", desc: "Coca de 2 L", price: "R$ 15,00" },
      { name: "Fanta 2 L", desc: "Fanta de 2 L", price: "R$ 13,00" },
      { name: "Guaraná 2 L", desc: "Guaraná de 2 L", price: "R$ 13,50" },
      { name: "Energético", desc: "Lata de energético", price: "R$ 13,00" },
      { name: "Brahma", desc: "Lata de Brahma", price: "R$ 5,50" },
      { name: "Original", desc: "Lata de Original", price: "R$ 7,00" },
      { name: "Budweiser", desc: "Lata de Budweiser", price: "R$ 7,00" },
      { name: "Heineken", desc: "Lata de Heineken", price: "R$ 8,00" },
    ],
  },
  {
    slug: "Choop Pilsen",
    icon: "🍺",
    title: "Choop Pilsen",
    items: [
      { name: "Caneca", desc: "Caneca de 400 ml", price: "R$ 8,00" },
      { name: "Torre 2,5", desc: "Torre de 2,5 L", price: "R$ 59,00" },
      { name: "Torre 3,5", desc: "Torre de 3,5 L", price: "R$ 79,00" },
    ]
  },
  {
    slug: "Choop de vinho",
    icon: "🍺",
    title: "Choop de vinho",
    items: [
      { name: "Caneca", desc: "Caneca de 400 ml", price: "R$ 10,00" },
      { name: "Torre 2,5", desc: "Torre de 2,5 L", price: "R$ 66,00" },
      { name: "Torre 3,5", desc: "Torre de 3,5 L", price: "R$ 87,00" },
    ]
  },
  {
    slug: "sorvetes",
    icon: "🍦",
    title: "Sorvetes",
    items: [
      { name: "Casquinha", desc: "Casquinha Baunilha, Misto ou Chocolate", price: "R$ 5,00" },
      { name: "Cascão", desc: "Cascão Baunilha, Misto ou Chocolate", price: "R$ 7,00" },
      { name: "Copinho 180 ml", desc: "Copinho de Chocolate, misto ou baunilha, 180ml", price: "R$ 5,00" },
      { name: "copo 300 ml", desc: "Copo de Chocolate, misto ou baunilha, 300 ml", price: "R$ 7,00" },
      { name: "Milk-shake 300 ml", desc: "Milk-shake de Chocolate, misto ou baunilha, 300 ml", price: "R$ 12,00" },
      { name: "Milk-shake 500 ml", desc: "Milk-shake de Chocolate, misto ou baunilha, 500 ml", price: "R$ 17,00" },
    ],
  },
  {
    slug: "caldo-de-cana",
    icon: "🎋",
    title: "Caldo de Cana de Limão, Abacaxi e Maracujá",
    items: [
      { name: "Copo 300 ml", desc: "300ml, moído na hora", price: "R$ 4,50" },
      { name: "Copo 400 ml", desc: "400ml, moído na hora", price: "R$ 6,00" },
      { name: "Copo 500 ml", desc: "500ml, moído na hora", price: "R$ 7,50" },
      { name: "Garrafinha 500 ml", desc: "500  ml, moído na hora", price: "R$ 9,00" },
      { name: "Garrafinha 1 L", desc: "1 L, moído na hora", price: "R$ 16,00" },
      { name: "Garrafinha 2 L", desc: "2 L, moído na hora", price: "R$ 28,00" },
    ],
  },
];